export const REQUEST_HEADER = {
  "Content-Type": "application/json",
  "Access-Control-Allow-Origin": "**",
  "Access-Control-Allow-Headers": "Origin, Content-Type, Accept",
  Authorization: "",
};
//Brand
export const SET_ALL_BRAND = "SET_ALL_BRAND";
export const SET_BRAND_ADD = "SET_BRAND_ADD";
export const SET_BRAND_OPTIONS = "SET_BRAND_OPTIONS";
export const SET_UPDATE_BRAND = "SET_UPDATE_BRAND";

//News
export const SET_NEWS_ADD = "SET_NEWS_ADD",
  SET_NEWS_ALL = "SET_NEWS_ALL";

//Blogs

export const SET_BOLOG_ALL = "SET_BOLOG_ALL",
  SET_BOLOG_ADD = "SET_BOLOG_ADD",
  SET_BOLOG_UPDATE = "SET_BOLOG_UPDATE";

//Category
export const SET_CATEGORIES = "SET_CATEGORIES",
  SET_CATEGORY_ADD = "SET_CATEGORY_ADD",
  SET_CATEGORY_OPTIONS = "SET_CATEGORY_OPTIONS",
  SET_UPDATE_CATEGORY = "SET_UPDATE_CATEGORY";

//Item
export const SET_ALL_ITEM = "SET_ALL_ITEM",
  SET_DELETE_ITEM = "SET_DELETE_ITEM",
  SET_ITEM = "SET_ITEM",
  SET_ITEM_ADD = "SET_ITEM_ADD",
  SET_ITEM_OPTIONS = "SET_ITEM_OPTIONS",
  SET_UPDATE_ITEM = "SET_UPDATE_ITEM";

//User
export const SET_CURRENT_USER = "SET_CURRENT_USER";

//Product
export const SET_PRODUCT_PRICE_BY_RANGE = "SET_PRODUCT_PRICE_BY_RANGE",
  SET_SEARCH_PRODUCT_OPTIONS = "SET_SEARCH_PRODUCT_OPTIONS";

//Filter State Manegment Type
export const SET_IS_FILTER_ACTIVE = "SET_IS_FILTER_ACTIVE",
  SET_FILTER_RANGE_VALUE = "SET_FILTER_RANGE_VALUE",
  SET_FILTER_BRANDS = "SET_FILTER_BRANDS";

//Compare State Manegment Type
export const CLEAR_ITEMS_FROM_COMPARE_LIST = "CLEAR_ITEMS_FROM_COMPARE_LIST",
  SET_ITEM_TO_COMPARE_LIST = "SET_ITEM_TO_COMPARE_LIST",
  SET_REMOVE_ITEM_TO_COMPARE_LIST = "SET_REMOVE_ITEM_TO_COMPARE_LIST";
